#!/usr/bin/env python

#
# Nagios plugin to check if current operating system version is outdated.
#

import sys
import argparse
from datetime import datetime, date, timedelta
import subprocess
import urllib2
import csv
from StringIO import StringIO
import traceback


debianDistroDataUrl = "https://anonscm.debian.org/git/collab-maint/distro-info-data.git/plain/debian.csv"
ubuntuDistroDataUrl = "https://anonscm.debian.org/git/collab-maint/distro-info-data.git/plain/ubuntu.csv"


def checkDebianUbuntu(nagiosOutput, distroDataUrl, eolWarningDays, eolCriticalDays,
    releaseWarningDays, releaseCriticalDays, checkForLTS=False, checkForServer=False):
    """
    Check currently installed Debian (or Ubuntu) release against online data from from distro-info-data package.
    """
    try:
        csvText = urllib2.urlopen(distroDataUrl).read()
    except urllib2.URLError, e:
        extype, ex, tb = sys.exc_info()
        msg = traceback.format_exception_only(extype, ex)[-1].rstrip()
        raise RuntimeError, "error downloading \"%s\": %s" % (distroDataUrl, msg), tb

    currentCodename = subprocess.check_output(["lsb_release", "--codename", "--short"]).rstrip("\n")
    currentReleaseData = None

    csvFp = StringIO(csvText)
    csvReader = csv.DictReader(csvFp)

    for row in csvReader:
        if row["series"] == currentCodename:
            currentReleaseData = row
            break
    else:
        raise Exception("current release '%s' not found in release list" % currentCodename)

    def parseCsvDate(string):
        return datetime.strptime(string, "%Y-%m-%d").date()
    nowDate = date.today()

    # check if there is a newer release available (by continuing to read from CSV buffer):
    newestWarningUpgrade = None
    newestCriticalUpgrade = None
    newestAnyUpgrade = None
    for row in csvReader:
        if checkForLTS and not(row["version"].endswith(" LTS")):
            continue
        if row["release"] is not None:
            releaseDate = parseCsvDate(row["release"])
            if nowDate >= releaseDate + timedelta(days=releaseWarningDays):
                newestWarningUpgrade = row
            if nowDate >= releaseDate + timedelta(days=releaseCriticalDays):
                newestCriticalUpgrade = row
            if nowDate >= releaseDate:
                newestAnyUpgrade = row
    if newestCriticalUpgrade is not None:
        nagiosOutput.addResult(NagiosOutput.LEVEL_CRITICAL, "newer release '%s' (%s) is available" % (newestCriticalUpgrade["series"], newestCriticalUpgrade["version"]))
    elif newestWarningUpgrade is not None:
        nagiosOutput.addResult(NagiosOutput.LEVEL_WARN,     "newer release '%s' (%s) is available" % (newestWarningUpgrade["series"], newestWarningUpgrade["version"]))
    elif newestAnyUpgrade is not None:
        nagiosOutput.addResult(NagiosOutput.LEVEL_OK,       "newer release '%s' (%s) is available" % (newestAnyUpgrade["series"], newestAnyUpgrade["version"]))

    # check if current release is EOL
    if checkForServer and currentReleaseData.has_key("eol-server") and currentReleaseData["eol-server"] is not None:
        eolDate = parseCsvDate(currentReleaseData["eol-server"])
    else:
        eolDate = parseCsvDate(currentReleaseData["eol"])
    if eolDate:
        if nowDate > eolDate:
            msg = "release '%s' has been EOL for %d days" % (currentCodename, (nowDate - eolDate).days)
        else:
            msg = "release '%s' will be EOL in %d days" % (currentCodename, (eolDate - nowDate).days)
        if nowDate > eolDate - timedelta(days=eolCriticalDays):
            nagiosOutput.addResult(NagiosOutput.LEVEL_CRITICAL, msg)
        elif nowDate > eolDate - timedelta(days=eolWarningDays):
            nagiosOutput.addResult(NagiosOutput.LEVEL_WARN, msg)
        else:
            nagiosOutput.addResult(NagiosOutput.LEVEL_OK, msg)


class NagiosOutput:
    "Class for collecting results and aggregating them into a single status output."
    LEVEL_OK = 0
    LEVEL_WARN = 1
    LEVEL_CRITICAL = 2

    def __init__(self, name, verbose):
        self.name = name
        self.verbose = verbose
        self.level = self.LEVEL_OK
        self.messages = []
        sys.excepthook = self.handleException

    def handleException(self, exc_type, exc_value, exc_traceback):
        """Handler for any uncaught exception."""
        if self.verbose:
            traceback.print_tb(exc_traceback)
        print "%s UNKNOWN (%s: %s)" % (self.name, exc_type, exc_value)
        sys.exit(3)

    def addResult(self, level, msg):
        if level not in (self.LEVEL_OK, self.LEVEL_WARN, self.LEVEL_CRITICAL):
            raise Exception("invalid error level '%s'" % level)
        self.level = max(self.level, level)
        self.messages.append(msg)

    def reportAndExit(self):
        result = self.name + " "
        if self.level == self.LEVEL_OK:
            result += "OK"
        elif self.level == self.LEVEL_WARN:
            result += "WARNING"
        elif self.level == self.LEVEL_CRITICAL:
            result += "CRITICAL"
        else:
            raise Exception("invalid error level '%s'" % level)
        result += " - " + ("; ".join(self.messages))
        print result
        sys.exit(self.level)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Check whether OS release is outdated.")
    parser.add_argument("-v", "--verbose", action="store_true", help="increase output verbosity")
    parser.add_argument("--eolWarningDays", type=int, metavar="DAYS", default=30, help="set WARNING status if less than DAYS until end-of-life")
    parser.add_argument("--eolCriticalDays", type=int, metavar="DAYS", default=7, help="set CRITICAL status if less than DAYS until end-of-life")
    parser.add_argument("--releaseWarningDays", type=int, metavar="DAYS", default=0, help="set WARNING status if new release available for more than DAYS")
    parser.add_argument("--releaseCriticalDays", type=int, metavar="DAYS", default=30, help="set CRITICAL status if new release available for more than DAYS")
    parser.add_argument("--lts", action="store_true", help="[Ubuntu] check only for LTS releases")
    parser.add_argument("--server", action="store_true", help="[Ubuntu] check for server EOL dates")
    args = parser.parse_args()

    nagiosOutput = NagiosOutput("OSRELEASE", args.verbose)
    distro = subprocess.check_output(["lsb_release", "--id", "--short"]).rstrip("\n")
    if distro == "Debian":
        checkDebianUbuntu(nagiosOutput, debianDistroDataUrl, args.eolWarningDays, args.eolCriticalDays, args.releaseWarningDays, args.releaseCriticalDays)
    elif distro == "Ubuntu":
        checkDebianUbuntu(nagiosOutput, ubuntuDistroDataUrl, args.eolWarningDays, args.eolCriticalDays, args.releaseWarningDays, args.releaseCriticalDays, args.lts, args.server)
    else:
        raise Exception("unknown distribution '%s'" % distro)
    nagiosOutput.reportAndExit()
